# Generated by Django 6.0.3 on 2026-04-04 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('alert_type', models.CharField(choices=[('weather', 'Weather'), ('traffic', 'Traffic'), ('work', 'Work'), ('system', 'System')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin')], default='worker', max_length=10)),
                ('name', models.CharField(default='Raj Kumar', max_length=100)),
                ('occupation', models.CharField(default='Delivery Partner', max_length=100)),
                ('zone', models.CharField(default='Chennai - Medium Risk', max_length=100)),
                ('safety_score', models.IntegerField(default=82)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('earnings_protected', models.DecimalField(decimal_places=2, default=3240.0, max_digits=10)),
                ('confidence_score', models.IntegerField(default=87)),
                ('ai_insight', models.TextField(default='Based on recent weather patterns, there is a 68% probability of work disruption this week. Premium adjusted accordingly.')),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_history', to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WorkerShield Gold', max_length=100)),
                ('policy_id', models.CharField(default='SN-9920-X', max_length=50)),
                ('coverage_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('daily_premium', models.DecimalField(decimal_places=2, default=14, max_digits=8)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Rain Disruption', max_length=200)),
                ('duration_hours', models.IntegerField(default=3)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=120, max_digits=8)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.worker')),
            ],
        ),
    ]
