# Generated by Django 6.0.3 on 2026-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='checkout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Disputed', 'Disputed'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
    ]
