import { useEffect } from "react";
import { useState } from "react";
import Sidebar from "../components/layout/Sidebar";
import Topbar from "../components/layout/Topbar";

export default function Claims() {
  const [autoGenerated, setAutoGenerated] = useState(false);
  useEffect(() => {
  setTimeout(() => {
    setAutoGenerated(true);
  }, 1500);
}, []);

  const [status, setStatus] = useState("None");

  const handleClaim = () => {
    setStatus("Submitted");

    setTimeout(() => setStatus("Processing"), 2000);
    setTimeout(() => setStatus("Approved"), 4000);
    setTimeout(() => setStatus("Paid"), 6000);
  };



  return (
    <div className="flex">
      <Sidebar />

      <div className="flex-1 p-6 bg-[#0f1117] min-h-screen">
      <Topbar />
        <h1 className="text-3xl font-bold mb-6">Claims</h1>

{!autoGenerated && (
  <p className="text-yellow-400 animate-pulse">
    Generating claim from live data...
  </p>
)}
        {/* CLAIM CARD */}
        <div className="bg-[#1a1d24] p-6 rounded-2xl shadow mb-6">
          <h2 className="text-xl font-semibold mb-3">
            Auto Claim Detection
          </h2>

          <p>Reason: Rain Disruption</p>
          <p>Duration: 3 hours</p>
          <p className="font-bold text-lg">Payout: ₹120</p>
          <br/>
          <button
            onClick={handleClaim}
            className="bg-[#2563eb] hover:bg-[#1d4ed8] text-white px-5 py-2 rounded-md transition"
          >
        Submit Claim
          </button>
        </div>

        {/* STATUS */}
        <div className="bg-[#1a1d24] p-6 rounded-2xl shadow mb-6">
          <h2 className="text-lg font-semibold mb-2">
            Claim Status
          </h2>

          <p className="text-xl font-bold text-blue-600 animate-pulse">
            {status}
          </p>
        </div>

        {/* HISTORY */}
        <div className="bg-[#1a1d24] p-6 rounded-2xl shadow">
          <h2 className="font-semibold mb-3">Past Claims</h2>

          <div className="flex justify-between border-b py-2">
            <span>Rain</span>
            <span>₹120</span>
          </div>

          <div className="flex justify-between border-b py-2">
            <span>Traffic</span>
            <span>₹80</span>

            <p className="text-xl font-bold text-blue-600">
  {status}
</p>

{status === "Approved" && (
  <p className="text-yellow-400 animate-pulse">
    💸 Releasing payout...
  </p>
)}
          </div>
        </div>
      </div>
    </div>
  );
}