import React from 'react';
import { useEffect, useState } from "react";
import Sidebar from "../components/layout/Sidebar";
import Topbar from "../components/layout/Topbar";
import { getClaims, submitClaim, updateClaimStatus } from "../api";

export default function Claims() {
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [status, setStatus] = useState("None");
  const [pastClaims, setPastClaims] = useState([]);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    // Load past claims from backend
    getClaims()
      .then(setPastClaims)
      .catch((err) => console.error("Failed to fetch claims:", err));

    setTimeout(() => setAutoGenerated(true), 1500);
  }, []);

  const handleClaim = async () => {
    setSubmitting(true);
    try {
      // POST new claim to backend
      const newClaim = await submitClaim({
        reason: "Rain Disruption",
        duration_hours: 3,
        payout_amount: 120,
      });
      setStatus("Submitted");

      setTimeout(() => {
        setStatus("Processing");
        updateClaimStatus(newClaim.id, "Processing").catch(console.error);
      }, 2000);

      setTimeout(() => {
        setStatus("Approved");
        updateClaimStatus(newClaim.id, "Approved").catch(console.error);
      }, 4000);

      setTimeout(() => {
        setStatus("Paid");
        updateClaimStatus(newClaim.id, "Paid").catch(console.error);
        // Refresh past claims list
        getClaims().then(setPastClaims).catch(console.error);
      }, 6000);
    } catch (err) {
      console.error("Failed to submit claim:", err);
      setStatus("Error");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex">
      <Sidebar />

      <div className="flex-1 p-6 bg-[#0f1117] min-h-screen text-white">
        <Topbar />
        <h1 className="text-3xl font-bold mb-6">Claims</h1>

        {!autoGenerated && (
          <p className="text-yellow-400 animate-pulse">
            Generating claim from live data...
          </p>
        )}

        {/* CLAIM CARD */}
        <div className="bg-[#1a1d24] p-6 rounded-2xl shadow mb-6">
          <h2 className="text-xl font-semibold mb-3">Auto Claim Detection</h2>
          <p>Reason: Rain Disruption</p>
          <p>Duration: 3 hours</p>
          <p className="font-bold text-lg">Payout: ₹120</p>
          <br />
          <button
            onClick={handleClaim}
            disabled={submitting || status !== "None"}
            className="bg-[#2563eb] hover:bg-[#1d4ed8] disabled:opacity-50 text-white px-5 py-2 rounded-md transition"
          >
            {submitting ? "Submitting..." : "Submit Claim"}
          </button>
        </div>

        {/* STATUS */}
        <div className="bg-[#1a1d24] p-6 rounded-2xl shadow mb-6">
          <h2 className="text-lg font-semibold mb-2">Claim Status</h2>
          <p className="text-xl font-bold text-blue-400 animate-pulse">{status}</p>
          {status === "Approved" && (
            <p className="text-yellow-400 animate-pulse mt-2">
              💸 Releasing payout...
            </p>
          )}
        </div>

        {/* HISTORY */}
        <div className="bg-[#1a1d24] p-6 rounded-2xl shadow">
          <h2 className="font-semibold mb-3">Past Claims</h2>
          {pastClaims.length === 0 ? (
            <p className="text-gray-500 text-sm">No past claims.</p>
          ) : (
            pastClaims.map((c) => (
              <div key={c.id} className="flex justify-between border-b border-[#2a2f3a] py-2 text-sm">
                <span>{c.reason}</span>
                <span className="text-green-400">₹{c.payout_amount}</span>
                <span className={`text-xs px-2 py-0.5 rounded ${
                  c.status === "Paid" ? "bg-green-900 text-green-300" :
                  c.status === "Approved" ? "bg-blue-900 text-blue-300" :
                  "bg-gray-700 text-gray-300"
                }`}>
                  {c.status}
                </span>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}